---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edc-dataplane.fullname" . }}-secret
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    {{- include "edc-dataplane.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
