image:
  tag: $ARGOCD_APP_REVISION

springprofile: int

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: "traceability.int.demo.catena-x.net"
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
      - "traceability.int.demo.catena-x.net"
      # Default secret for certificate creation already provided to your namespace
      secretName: trace-backend-tls-secret

mailserver:
  password: <path:traceability-foss/data/int#mailserverPassword>

datasource:
  url: jdbc:postgresql://product-traceability-foss-backend-postgresql:5432/trace
  username: trace
  password: <path:traceability-foss/data/int/database#tracePassword>

keycloak:
  oauth2:
    clientId: <path:traceability-foss/data/int/keycloak/oauth2#clientId>
    clientSecret: <path:traceability-foss/data/int/keycloak/oauth2#clientSecret>

postgresql:
  enabled: true
  secret:
    initUserDbSql: "<path:traceability-foss/data/int/database#initUserDb.sql>"
  auth:
    postgresPassword: "<path:traceability-foss/data/int/database#postgresPassword>"
  primary:
    extraVolumeMounts:
      - name: initdb
        mountPath: "/docker-entrypoint-initdb.d"
      - name: initdb-secrets
        mountPath: "/secrets"
    extraVolumes:
      - name: initdb
        emptyDir: {}
      - name: initdb-secrets
        secret:
          secretName: secret-postgres-init-db-user
    initContainers:
      - name: initdb
        image: ghcr.io/catenax-ng/product-portal-cd_initdb:latest
        imagePullPolicy: Always
        command:
          - sh
        args:
          - -c
          - |
            echo "Copying initdb secret sqls..."
            cp /secrets/* /docker-entrypoint-initdb.d
            echo "Copying initdb sqls..."
            cp -R /import/* /docker-entrypoint-initdb.d
        volumeMounts:
          - name: initdb
            mountPath: "/docker-entrypoint-initdb.d"
          - name: initdb-secrets
            mountPath: "/secrets"

pgadmin4:
  enabled: true
  strategy:
    type: Recreate
  networkPolicy:
    enabled: false
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - host: trace-pgadmin4.int.demo.catena-x.net
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - trace-pgadmin4.int.demo.catena-x.net
        secretName: trace-pgadmin4-tls-secret
  env:
    email: pgadmin4@trace.foss
    password: "<path:traceability-foss/data/int/database#pgadminPassword>"
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
