---
apiVersion: v2
name: edc-controlplane
description: >-
  EDC Control-Plane - The Eclipse DataSpaceConnector administration layer with responsibility of resource management and govern contracts and data transfers
home: https://github.com/catenax-ng/product-edc/deployment/helm/edc-controlplane
type: application
appVersion: "0.1.1"
version: 0.1.1
maintainers: []
dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.x.x
    condition: edcPostgresql.enabled
    alias: edcPostgresql
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.x.x
    condition: registryPostgresql.enabled
    alias: registryPostgresql
