{{- $fullName := include "edc-controlplane.fullname" . }}
{{- if eq (.Values.networkPolicy.enabled | toString) "true"  }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    {{- include "edc-controlplane.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
    {{- include "edc-controlplane.selectorLabels" . | nindent 6 }}
  ingress:
  - ports:
      - protocol: TCP
        port: {{ .Values.edc.endpoints.default.port }}
      - protocol: TCP
        port: {{ .Values.edc.endpoints.data.port }}
      - protocol: TCP
        port: {{ .Values.edc.endpoints.validation.port }}
      - protocol: TCP
        port: {{ .Values.edc.endpoints.control.port }}
      - protocol: TCP
        port: {{ .Values.edc.endpoints.ids.port }}
      - protocol: TCP
        port: {{ .Values.edc.endpoints.metrics.port }}
    from:
    {{- toYaml .Values.networkPolicy.from | nindent 4}}
  policyTypes:
  - Ingress
{{- end }}

